# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b6d4f084c5b871ad537e82cd8ef1313aff090d163c67817a04c809686b414dd3340b01ee995ccaa547810605b5ca3cfaff7245e5f733e5e00501a36b0f21f2b

test:
  secret_key_base: f5459511f491d2bb3132e85a8b267294b7cdd34150f63754fb33172c3d1f57818aa1456b95bc61a11a6563da4d98c81e8fca48e52bd08649d97e9db70a8b83d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
